<a href="https://colab.research.google.com/github/KeilaNLima/Projeto-Machine-Learning/blob/master/Pessoas_com_doen%C3%A7a_de_Verrugas_e_tratamento_com_Crioterapia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gerando modelo de Machine Learning (classificação)
# Domínio: Pessoas com doença de Verrugas e tratamento com Crioterapia.
# Keila Nunes de Lima

In [ ]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
# carrega o dataset com os dados para o treinamento e validacao
df_crioterapia_treino = pd.read_csv("dados_cryotherapy.csv", encoding="utf-8")

In [ ]:
df_crioterapia_treino.describe()

Sexo      Idade      Tempo  Numero_Verrugas       Tipo  \
count  90.000000  90.000000  90.000000        90.000000  90.000000   
mean    1.477778  28.600000   7.344444         5.511111   1.700000   
std     0.502304  13.360852   3.379253         3.567155   0.905042   
min     1.000000  15.000000   1.000000         1.000000   1.000000   
25%     1.000000  18.000000   4.000000         2.000000   1.000000   
50%     1.000000  25.500000   8.000000         5.000000   1.000000   
75%     2.000000  35.000000  10.000000         8.000000   3.000000   
max     2.000000  67.000000  12.000000        12.000000   3.000000   

             Area  Resultado_Tratamento  
count   90.000000             90.000000  
mean    85.833333              0.533333  
std    131.733153              0.501683  
min      4.000000              0.000000  
25%     20.000000              0.000000  
50%     70.000000              1.000000  
75%    100.000000              1.000000  
max    750.000000              1.000000

In [ ]:
# Verificando o formato dos dados
df_crioterapia_treino.shape

(90, 7)

In [ ]:
# Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(df_crioterapia_treino[['Sexo', 'Idade', 'Numero_Verrugas', 'Tipo', 'Area']])
#De#finição do atributo de classificacao
data_classif = np.array(df_crioterapia_treino['Resultado_Tratamento'])

In [ ]:
# Verificando as primeiras linhas do dataset
df_crioterapia_treino.head(5)

Sexo  Idade  Tempo  Numero_Verrugas  Tipo  Area  Resultado_Tratamento
0     1     35     12                5     1   100                     0
1     1     29      7                5     1    96                     1
2     1     50      8                1     3   132                     0
3     1     32     11                7     3   750                     0
4     1     67      9                1     1    42                     0

In [ ]:
# Verificando as ultimas linhas do dataset
df_crioterapia_treino.tail(5)

Sexo  Idade  Tempo  Numero_Verrugas  Tipo  Area  Resultado_Tratamento
85     2     34     12                3     3    95                     0
86     2     20      3                6     1    75                     1
87     2     35      8                8     3   100                     0
88     1     24     10               10     1    20                     1
89     1     19      8                8     1   160                     1

In [ ]:
# Identificando a correlação entre as variáveis
# Correlação não implica causalidade
def plot_corr(df_crioterapia_treino, size=35):
    corr = dados_mamiferos_treino.corr()
    fig, ax = plt.subplots(figsize = (size, size))
    ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns)
    plt.yticks(range(len(corr.columns)), corr.columns)

In [ ]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [ ]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[  1  16   3   2  60]
 [  1  34   1   3 150]
 [  1  28   3   1 100]
 [  1  29   5   1  96]
 [  1  15  11   1   4]
 [  2  21   5   1  35]
 [  1  35   2   1 100]
 [  1  50   1   3 132]
 [  1  15   2   1   4]
 [  1  17  10   1  63]
 [  1  17  12   1  10]
 [  2  22   9   1  70]
 [  2  20   6   1  75]
 [  1  27   7   1   6]
 [  1  34   1   3  95]
 [  2  67  12   3  42]
 [  2  23  12   3  72]
 [  1  19   8   1 160]
 [  1  20  11   1  75]
 [  1  30   2   1 115]
 [  1  18   1   1  80]
 [  1  36   2   1   8]
 [  2  21   7   1  35]
 [  1  23   7   3  72]
 [  2  30   8   3 115]
 [  2  18   1   1  80]
 [  1  20   3   1   6]
 [  1  67  11   3  20]
 [  2  23   5   3  72]
 [  1  59   3   3  20]
 [  2  35   6   3 100]
 [  2  40   1   2  80]
 [  1  24  10   1  20]
 [  1  41   2   2  20]
 [  2  18   8   1  80]
 [  1  35   9   1 100]
 [  2  32   4   3 750]
 [  2  17   3   1  63]
 [  1  32   7   3 750]
 [  2  22   2   1  70]
 [  2  40   6   2  80]
 [  1  24

In [ ]:
# Imprimindo os resultados
print("{0:0.2f}% nos dados de treino".format((len(x_treino)/len(df_crioterapia_treino.index)) * 100))
print("{0:0.2f}% nos dados de teste".format((len(x_val)/len(df_crioterapia_treino.index)) * 100))

70.00% nos dados de treino
30.00% nos dados de teste


In [ ]:
# - Aplicando o Algoritmo com o Naive Bayes - GaussianNB.

In [ ]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [ ]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.7777777777777778
Na Base de Treinamento


In [ ]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.7407407407407407
na Base de Teste


In [ ]:
from sklearn import metrics

In [ ]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[10  3]
 [ 4 10]]

Classification Report
              precision    recall  f1-score   support

           1       0.71      0.77      0.74        13
           0       0.77      0.71      0.74        14

    accuracy                           0.74        27
   macro avg       0.74      0.74      0.74        27
weighted avg       0.74      0.74      0.74        27

